apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-system-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback-system-backend
  template:
    metadata:
      labels:
        app: feedback-system-backend
    spec:
      containers:
      - name: feedback-system-backend-container
        image: arpitsrivastava529/feedback-system-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/feedback"
        - name: PORT
          value: "8080"