apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-system-frontend
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: feedback-system-frontend
  template:
    metadata:
      labels:
        app: feedback-system-frontend
    spec:
      containers:
      - name: feedback-system-container
        image: arpitsrivastava529/feedback-system-frontend:latest
        ports:
          - containerPort: 3000
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://localhost:8080"