apiVersion: v1
kind: Service
metadata:
  name: feedback-system-service
spec:
  selector:
    app: feedback-system-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
